#!/usr/bin/env python3

import colorsys

def rgb2hex(r, g, b, *a):
    return '{:02x}{:02x}{:02x}'.format(r,g,b)


for x in range(1366//10+1):
    for y in range(768):
        (r, g, b) = colorsys.hsv_to_rgb((x*10+y*2)/400, 1.0, 1.0)
        R, G, B = int(255 * r), int(255 * g), int(255 * b)
        print(f"PX {x*10} {y} {rgb2hex(R,G,B)}")
for x in range(1366):
    for y in range(768//10+1):
        (r, g, b) = colorsys.hsv_to_rgb((x+y*10*2)/400, 1.0, 1.0)
        R, G, B = int(255 * r), int(255 * g), int(255 * b)
        print(f"PX {x} {y*10} {rgb2hex(R,G,B)}")
